### ISSUE TITLE
The ability to remove or edit round entries so sing in times can be changed or the round can be completely removed

### ISSUE THREAD

**Issue by Scholesy46** [TJSteel/OnlineRacingManager#54] opened 2020-02-04 19:00 UTC

**Comment by TJSteel** [comment] 2020-02-06 14:43
sign in times can be changed as this was fixed in a previous bug,

however deleting the round is not an option, as it's a delete function, once implemented this will be something for administrators only, there is another issue for allowing the edit of race rounds so I'm closing this issue as a duplicate of the following:
https://github.com/TJSteel/OnlineRacingManager/issues/42

**Closed by TJSteel** 2020-02-06 14:43 UTC
Labels: duplicate, enhancement
